### ISSUE TITLE
Loading spinner page on pharos.org doesn't load

### ISSUE THREAD

**Issue by lorilundy711** [ithaka/pharos#756]
**Expected behavior**
The page should load as the rest of the component pages do with documentation.

**Actual behavior**
The page is blank and appears to be broken

**Steps to reproduce the issue**

1. Go to https://pharos.jstor.org/components/loading-spinner
2. Observe a blank page.

**Additional information**
It is possible that this component does not have written documentation and that that the page on pharos.org needs to be designed.

**Comment by daneah** [comment]
There does exist a [mild amount of existing guidance](https://github.com/ithaka/pharos/blob/develop/packages/pharos-site/static/guidelines/loading-spinner.docs.mdx), so although we can probably stand to enhance it, doesn't seem to be a direct cause of the issue. Going a step further in the debugging, I see this in the browser console on that page:

```javascript
react-dom.production.min.js:188 TypeError: d.trim is not a function
    at jo (CodeBlock.tsx:53:27)
    at go (react-dom.production.min.js:160:137)
    at xi (react-dom.production.min.js:289:337)
    at bs (react-dom.production.min.js:279:389)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at ls (react-dom.production.min.js:270:88)
    at as (react-dom.production.min.js:267:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.R (scheduler.production.min.js:14:128)
fu @ react-dom.production.min.js:188

react-dom.production.min.js:127 Uncaught TypeError: d.trim is not a function
    at jo (CodeBlock.tsx:53:27)
    at go (react-dom.production.min.js:160:137)
    at xi (react-dom.production.min.js:289:337)
    at bs (react-dom.production.min.js:279:389)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at ls (react-dom.production.min.js:270:88)
    at as (react-dom.production.min.js:267:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.R (scheduler.production.min.js:14:128)

standalone.mjs:23 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'languages')
    at standalone.mjs:23:694
    at Array.flatMap (<anonymous>)
    at Ct (standalone.mjs:23:681)
    at Sn (standalone.mjs:26:12000)
    at Kn (standalone.mjs:32:273)
    at standalone.mjs:34:800
    at Object.xo (standalone.mjs:34:869)
    at jo (CodeBlock.tsx:21:5)
    at go (react-dom.production.min.js:160:137)
    at xi (react-dom.production.min.js:289:337)
```

I haven't yet made heads nor tails of that, but I suspect something in the chaing of Gatsby + React + react-live or something of the sort.

**Comment by grcope** [comment]
Unable to load content on the page for paginations: https://pharos.jstor.org/components/pagination
